uName = input("What's your name? ")
print("Nice name!")
uFood = input("What's your favorite food? ")
print("Uhnnn...Yummy!")
uMusic = input("What's your favorite music? ")
print("Good song!")
uHome = input("What is the name of the city you live? ")
print("Wow, I know this city!")
print()
print("Your name is")
print(uName)
print("Love to eat")
print(uFood)
print("Feels good to listen")
print(uMusic)
print("And lives well in")
print(uHome)
print("You rock!!!")